dist: trusty
sudo: false
language: generic
branches:
  only:
    - master

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install tox
# command to run tests
script:
  - tox -r -e py27
