dist: trusty
sudo: true
language: generic
branches:
  only:
    - master

# command to install dependencies
install:
  - sudo pip install -r requirements.txt
  - sudo pip install -r test-requirements.txt
  - sudo pip install tox
# command to run tests
script:
  - sudo tox -r -e py27
